apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    app: dr-demo-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odf-storage-pvc
  namespace: demo-app
  labels:
    app: dr-demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbdmirror
---
apiVersion: v1
kind: Pod
metadata:
  name: odf-app-pod
  namespace: demo-app
  labels:
    app: dr-demo-app
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app-container
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      command: [ "sleep", "infinity" ]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: odf-volume
  volumes:
    - name: odf-volume
      persistentVolumeClaim:
        claimName: odf-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odf-app-service
  namespace: demo-app
  labels:
    app: dr-demo-app
spec:
  type: ClusterIP
  selector:
    app: dr-demo-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
